// gridsome-go/src/pages/Index.vue
<template>
  <main>
    <h1>Gridsome + Go API</h1>
    <h2>
      Deployed with
      <a href="https://zeit.co/docs" target="_blank" rel="noreferrer noopener">ZEIT Now</a>
      !
    </h2>
    <p>
      <a
        href="https://github.com/zeit/now-examples/blob/master/gridsome-go"
        target="_blank"
        rel="noreferrer noopener"
      >This project</a> is a
      <a href="https://gridsome.org/">Gridsome</a>
      app with three directories,
      <code>/static</code>
      for static assets,
      <code>/src</code> for components and content, and
      <code>/api</code>
      which contains a serverless
      <a href="https://golang.org/">Go</a>
      function. See
      <a href="/api/date.go">
        <code>api/date.go</code> for the Date API with Go
      </a>.
    </p>
    <br />
    <h2>The date according to Go is:</h2>
    <p>{{date}}</p>
  </main>
</template>

<script>
export default {
  name: "Gridsome + Go API",
  metaInfo: {
    title: "Gridsome + Go API"
  },
  props: {
    date: String
  },
  mounted() {
    return fetch("/api/date.go")
      .then(response => response.text())
      .then(date => (this.date = date));
  }
};
</script>

<style>
main {
  align-content: center;
  box-sizing: border-box;
  display: grid;
  font-family: "SF Pro Text", "SF Pro Icons", "Helvetica Neue", "Helvetica",
    "Arial", sans-serif;
  hyphens: auto;
  line-height: 1.65;
  margin: 0 auto;
  max-width: 680px;
  min-height: 100vh;
  padding: 72px 0;
  text-align: center;
}
h1 {
  font-size: 45px;
}
h2 {
  margin-top: 1.5em;
}
p {
  font-size: 16px;
}
a {
  border-bottom: 1px solid white;
  color: #0076ff;
  cursor: pointer;
  text-decoration: none;
  transition: all 0.2s ease;
}
a:hover {
  border-bottom: 1px solid #0076ff;
}
code,
pre {
  color: #d400ff;
  font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,
    Bitstream Vera Sans Mono, Courier New, monospace, serif;
  font-size: 0.92em;
}
code:before,
code:after {
  content: "\`";
}
</style>

// umijs-go/src/pages/index.tsx
import React, { useEffect, useState } from 'react';
import { RouterTypes } from 'umi';

const App: React.SFC<RouterTypes> = () => {
  const [date, setDate] = useState(null);
  useEffect(() => {
    async function getDate() {
      const res = await fetch('/api/date');
      const newDate = await res.text();
      setDate(newDate);
    }
    getDate();
  }, []);
  return (
    <main>
      <h1>UmiJS + Go API</h1>
      <h2>
        Deployed with{' '}
        <a
          href="https://zeit.co/docs"
          target="_blank"
          rel="noreferrer noopener"
        >
          ZEIT Now
        </a>
        !
      </h2>
      <p>
        <a
          href="https://github.com/zeit/now-examples/blob/master/umijs-go"
          target="_blank"
          rel="noreferrer noopener"
        >
          This project
        </a>{' '}
        is a <a href="https://umijs.org/">UmiJS</a> app with two directories,{' '}
        <code>/pages</code> for content and components, and <code>/api</code>{' '}
        which contains a serverless <a href="https://golang.org/">Go</a>{' '}
        function. See{' '}
        <a href="/api/date">
          <code>api/date</code> for the Date API with Go
        </a>
        .
      </p>
      <br />
      <h2>The date according to Go is:</h2>
      <p>{date ? date : 'Loading date...'}</p>
    </main>
  );
};

export default App;
